-- Panel monitor identity. GENERATED by scripts/derive-monitor.sh — edit that,
-- or re-run it, rather than hand-editing this file.
--
-- Pinned by DESCRIPTION, never by connector name: connector names like
-- "HDMI-A-1" reorder on hotplug and would silently move the panel.
--
-- Re-derive here or on other hardware:
--     ./scripts/derive-monitor.sh
-- or read it straight off Hyprland:
--     hyprctl monitors -j | jq -r '.[] | "\(.name)  \(.width)x\(.height)  \(.description)"'
--
-- Discovered on connector HDMI-A-1 at 2026-08-24T17:40:44Z.
return {
  description = "Lenovo Group Limited LEN L1950wD B3432845",

  mode = "1024x600@60",

  -- The output's ACTUAL position, not "auto". With auto, enumeration order
  -- decides the layout. The LG DisplayPort monitor is the primary desktop at
  -- 0x0; this panel sits immediately to its right and owns only the named
  -- `roost` workspace. Sunshine's retained headless output sits after it.
  position = "3840x0",
  scale = 1,

  -- Escape hatch: a raw connector name, used ONLY for outputs that report no
  -- description (Hyprland headless outputs). Leave nil for real hardware so the
  -- description-based selector is used.
  output = nil,

  -- Flipped by hand; derive-monitor.sh always writes false.
  verified = true,
}
