-- Panel monitor identity. GENERATED by scripts/derive-monitor.sh — edit that,
-- or re-run it, rather than hand-editing this file.
--
-- Pinned by DESCRIPTION, never by connector name: connector names like
-- "HDMI-A-1" reorder on hotplug and would silently move the panel.
--
-- Re-derive here or on other hardware:
--     ./scripts/derive-monitor.sh
-- or read it straight off Hyprland:
--     hyprctl monitors -j | jq -r '.[] | "\(.name)  \(.width)x\(.height)  \(.description)"'
--
-- Discovered on connector HDMI-A-1 at 2026-08-23T00:55:00Z.
return {
  description = "Lenovo Group Limited LEN L1950wD B3432845",

  mode = "1024x600@60",
  position = "auto",
  scale = 1,

  -- Escape hatch: a raw connector name, used ONLY for outputs that report no
  -- description (Hyprland headless outputs). Leave nil for real hardware so the
  -- description-based selector is used.
  output = nil,

  -- This script proves the output is PRESENT. It cannot prove the pin works,
  -- so it never sets this. Flip it by hand once the panel renders for real.
  verified = false,
}
