#!/usr/bin/env bash
# Re-derive the panel's monitor DESCRIPTION and write config/hypr/roost-monitor.lua.
#
# The Hyprland rules pin the panel by description, never by connector name
# (HDMI-A-1, DP-1 …), because connector names reorder on hotplug and would
# silently move the panel to the wrong output.
#
#   ./scripts/derive-monitor.sh              # auto-detect the 1024x600 output
#   ./scripts/derive-monitor.sh DP-2         # use a specific connector
#   ./scripts/derive-monitor.sh --list       # just show what is connected
#
# Then reload:  hyprctl reload && hyprctl configerrors

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_DIR}/config/hypr/roost-monitor.lua"
PANEL_W="${ROOST_PANEL_WIDTH:-1024}"
PANEL_H="${ROOST_PANEL_HEIGHT:-600}"

command -v hyprctl >/dev/null || { echo "hyprctl not found; is Hyprland running?" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq not found" >&2; exit 1; }

monitors_json=$(hyprctl monitors -j)

if [ "${1:-}" = "--list" ]; then
  echo "Connected outputs:"
  echo "$monitors_json" | jq -r '.[] | "  \(.name)  \(.width)x\(.height)@\(.refreshRate|floor)  description=\"\(.description)\""'
  exit 0
fi

if [ -n "${1:-}" ]; then
  selected=$(echo "$monitors_json" | jq --arg n "$1" '[.[] | select(.name == $n)]')
else
  selected=$(echo "$monitors_json" | jq --argjson w "$PANEL_W" --argjson h "$PANEL_H" \
    '[.[] | select(.width == $w and .height == $h)]')
fi

count=$(echo "$selected" | jq 'length')

if [ "$count" -eq 0 ]; then
  {
    echo "No matching output found."
    echo
    echo "Looked for ${PANEL_W}x${PANEL_H}. Currently connected:"
    echo "$monitors_json" | jq -r '.[] | "  \(.name)  \(.width)x\(.height)  description=\"\(.description)\""'
    echo
    echo "If the panel is plugged in but absent, check the connector is live:"
    echo "  for c in /sys/class/drm/card*-*/status; do echo \"\$c \$(cat \$c)\"; done"
    echo
    echo "Then re-run, or pass the connector explicitly:  $0 DP-2"
  } >&2
  exit 1
fi

if [ "$count" -gt 1 ]; then
  {
    echo "More than one output matches ${PANEL_W}x${PANEL_H}:"
    echo "$selected" | jq -r '.[] | "  \(.name)  description=\"\(.description)\""'
    echo "Pass the connector explicitly:  $0 <CONNECTOR>"
  } >&2
  exit 1
fi

name=$(echo "$selected" | jq -r '.[0].name')
description=$(echo "$selected" | jq -r '.[0].description')
width=$(echo "$selected" | jq -r '.[0].width')
height=$(echo "$selected" | jq -r '.[0].height')
refresh=$(echo "$selected" | jq -r '.[0].refreshRate | floor')

if [ -z "$description" ] || [ "$description" = "null" ]; then
  {
    echo "Output ${name} reports an EMPTY description, so it cannot be pinned by one."
    echo "Hyprland headless outputs behave this way; real panels do not."
    echo "If this really is your panel, set 'output = \"${name}\"' in ${OUT} by hand"
    echo "and accept that hotplug reordering can move it."
  } >&2
  exit 1
fi

cat > "$OUT" <<LUA
-- Panel monitor identity. GENERATED by scripts/derive-monitor.sh — edit that,
-- or re-run it, rather than hand-editing this file.
--
-- Pinned by DESCRIPTION, never by connector name: connector names like
-- "${name}" reorder on hotplug and would silently move the panel.
--
-- Re-derive here or on other hardware:
--     ./scripts/derive-monitor.sh
-- or read it straight off Hyprland:
--     hyprctl monitors -j | jq -r '.[] | "\\(.name)  \\(.width)x\\(.height)  \\(.description)"'
--
-- Discovered on connector ${name} at $(date -u +%Y-%m-%dT%H:%M:%SZ).
return {
  description = "${description}",

  mode = "${width}x${height}@${refresh}",
  position = "auto",
  scale = 1,

  -- Escape hatch: a raw connector name, used ONLY for outputs that report no
  -- description (Hyprland headless outputs). Leave nil for real hardware so the
  -- description-based selector is used.
  output = nil,

  verified = true,
}
LUA

echo "Wrote ${OUT}"
echo "  connector:   ${name}   (not used for matching — recorded for humans)"
echo "  description: ${description}"
echo "  mode:        ${width}x${height}@${refresh}"
echo
echo "Apply it:  hyprctl reload && hyprctl configerrors"
